#!/usr/bin/env bash

EVENT="$1"
MESSAGE="$2"
TIME="$3"
LOG_FILE="$4"

declare -A COLORS=(
    [NO]="\033[0m"
    # ORIGINAL
    [BLACK]="\033[0;30m"
    [RED]="\033[0;31m"
    [GREEN]="\033[0;32m"
    [ORANGE]="\033[0;33m"
    [BLUE]="\033[0;34m"
    [PURPLE]="\033[0;35m"
    [CYAN]="\033[0;36m"
    [GRAY]="\033[0;37m"
    # BOLD
    [BOLD_BLACK]="\033[1;30m"
    [BOLD_RED]="\033[1;31m"
    [BOLD_GREEN]="\033[1;32m"
    [BOLD_ORANGE]="\033[1;33m"
    [BOLD_BLUE]="\033[1;34m"
    [BOLD_PURPLE]="\033[1;35m"
    [BOLD_CYAN]="\033[1;36m"
    [BOLD_GRAY]="\033[1;37m"
)

declare -A EVENTS=(
    [END]="BLUE"
    [ERROR]="RED"
    [INFO]="GREEN"
    [RUN]="BLUE"
    [STATUS]="ORANGE"
)

if [[ -n "${EVENTS[$EVENT]}" ]]
then

    COLOR=${COLORS[${EVENTS[$EVENT]}]}

else

    COLOR=${COLORS[GRAY]}

fi

if [[ ${TIME} ]]
then

    NOW_TIME=`date +"%Y-%m-%d %H:%M:%S "`

fi

echo -e "${NOW_TIME}${COLOR}[${EVENT}] ${MESSAGE}${COLORS[NO]}"
